#pragma once

#include <arpa/inet.h>
#include <stdint.h>
#include <sys/random.h>

#include <array>

#include "../crypto/crypto.h"
#include <cstring>

#define MAX_PEERS 32
#define SESSION_KEY_LEN 32
#define MAX_PACKET_BITMAP_COUNT 64

enum
{
    PEER_DISCONNECTED,
    PEER_HANDSHAKING,
    PEER_ESTABLISHED
};

typedef struct
{
    uint32_t client_index;
    uint32_t server_index;

    uint64_t last_handshake_ts;

    uint64_t packet_count;

    std::array<
        bool,
        MAX_PACKET_BITMAP_COUNT>
        packet_bitmap;

    /*
     * Client keys received in handshake
     */
    CryptoContext::Key
        clientStaticPublicKey{};

    CryptoContext::Key
        clientEphemeralPublicKey{};

    /*
     * Generated by server
     */
    CryptoContext::EphemeralKeyPair
        serverEphemeral;

    /*
     * Active session keys
     */
    uint8_t session_send_key[
        SESSION_KEY_LEN];

    uint8_t session_recv_key[
        SESSION_KEY_LEN];

    /*
     * Previous keys retained during rekey
     */
    uint8_t prev_session_send_key[
        SESSION_KEY_LEN];

    uint8_t prev_session_recv_key[
        SESSION_KEY_LEN];

    uint64_t send_nonce;
    uint64_t recv_nonce;

    sockaddr_in endpoint;

    uint32_t vpn_ip;

    int state;

} peer_t;

extern peer_t peers[MAX_PEERS];

extern int peer_count;

void init_peers();

peer_t *add_peer(
    const uint8_t *clientStatic,
    const uint8_t *clientEphemeral,
    uint32_t index,
    uint64_t epoch_ts,
    sockaddr_in *addr);

peer_t *find_peer_by_ip(
    sockaddr_in *addr);

peer_t *find_peer_by_index(
    sockaddr_in *addr,
    uint32_t index);

peer_t *find_peer_by_vpn_ip(
    uint32_t addr);

void establish_session(
    peer_t *peer,
    const uint8_t *send_key,
    const uint8_t *recv_key);